robot_dim:
  length: 4.0
  width: 2.0
  safety_margin: 3.0  # Global safety margin (radius)

robots:
  - start:
      x: -30.0
      y: 0.0
    goal:
      x: 30.0
      y: 0.0
    color: "blue"
    max_vel: 1.0  # Robot 1 velocity

  - start:
      x: 30.0
      y: 0.0  # Changed y-position to 0
    goal:
      x: -30.0
      y: 0.0
    color: "green"
    max_vel: -1.0  # Robot 2 moves toward Robot 1

  - start:
      x: -30.0
      y: 5.0
    goal:
      x: 30.0
      y: 5.0
    color: "red"
    max_vel: 1.0  # Robot 3 velocity
