robot_dim:
  length: 0.2
  width: 0.2
  safety_margin: 3.0  # Radius for the safety circle

robots:
  # North → South
  - start:
      x: 0
      y: 0
    goal:
      x: 20
      y: 20
    color: "blue"
    max_vel: 1.7
    controller_frequency: 13


  