robot_dim:
  length: 4.0
  width: 2.0
  safety_margin: 3.0  # Radius for the safety circle

robots:
  # East → West
  - start:
      x: 30.0
      y: 0.0
    goal:
      x: -30.0
      y: 0.0
    color: "blue"
    max_vel: 2.0
    controller_frequency: 2

  # North → South
  - start:
      x: 0.0
      y: 30.0
    goal:
      x: 0.0
      y: -30.0
    color: "red"
    max_vel: 2.0
    controller_frequency: 2

  # West → East
  - start:
      x: -30.0
      y: 0.0
    goal:
      x: 30.0
      y: 0.0
    color: "green"
    max_vel: 2.0
    controller_frequency: 2

  # South → North
  - start:
      x: 0.0
      y: -30.0
    goal:
      x: 0.0
      y: 30.0
    color: "orange"
    max_vel: 2.0
    controller_frequency: 2
